CREATE DATABASE IF NOT EXISTS NutriSurvey;
USE NutriSurvey;

CREATE TABLE pengguna (
    id INT AUTO_INCREMENT PRIMARY KEY,
    nama VARCHAR(100) NOT NULL,
    email VARCHAR(100) UNIQUE NOT NULL,
    password VARCHAR(255) NOT NULL,
    tanggal_lahir DATE,
    jenis_kelamin VARCHAR(10),
    email_terverifikasi BOOLEAN DEFAULT FALSE,
    token_verifikasi VARCHAR(255),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE profil_nutrisi (
    id INT AUTO_INCREMENT PRIMARY KEY,
    user_id INT NOT NULL,
    tinggi_badan DECIMAL(5,1),
    berat_badan_awal DECIMAL(5,1),
    berat_badan_target DECIMAL(5,1),
    usia INT,
    jenis_kelamin VARCHAR(10),
    target_kalori INT DEFAULT 2000,
    target_protein INT DEFAULT 60,
    target_lemak INT DEFAULT 50,
    target_karbohidrat INT DEFAULT 65,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES pengguna(id) ON DELETE CASCADE
);

CREATE TABLE menu_makanan (
    id INT AUTO_INCREMENT PRIMARY KEY,
    nama_makanan VARCHAR(150) NOT NULL,
    kalori INT NOT NULL,
    protein DECIMAL(5,1) DEFAULT 0,
    lemak DECIMAL(5,1) DEFAULT 0,
    karbohidrat DECIMAL(5,1) DEFAULT 0,
    kategori VARCHAR(50),
    tipe_diet VARCHAR(50),
    gambar VARCHAR(255),
    emoji VARCHAR(10),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE konsumsi_harian (
    id INT AUTO_INCREMENT PRIMARY KEY,
    user_id INT NOT NULL,
    menu_id INT,
    nama_makanan VARCHAR(150),
    porsi DECIMAL(5,1) DEFAULT 1,
    kalori INT DEFAULT 0,
    protein DECIMAL(5,1) DEFAULT 0,
    lemak DECIMAL(5,1) DEFAULT 0,
    karbohidrat DECIMAL(5,1) DEFAULT 0,
    tanggal DATE NOT NULL,
    waktu_makan VARCHAR(20) DEFAULT 'Sarapan',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES pengguna(id) ON DELETE CASCADE,
    FOREIGN KEY (menu_id) REFERENCES menu_makanan(id) ON DELETE SET NULL
);

CREATE TABLE berat_badan (
    id INT AUTO_INCREMENT PRIMARY KEY,
    user_id INT NOT NULL,
    berat_badan DECIMAL(5,1) NOT NULL,
    tanggal DATE NOT NULL,
    catatan TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES pengguna(id) ON DELETE CASCADE
);

CREATE TABLE preferensi_pengguna (
    id INT AUTO_INCREMENT PRIMARY KEY,
    user_id INT NOT NULL,
    target_kalori INT DEFAULT 2000,
    preferensi_makan VARCHAR(50) DEFAULT 'semua',
    alasan_diet VARCHAR(50) DEFAULT 'jaga',
    tingkat_aktivitas VARCHAR(20) DEFAULT 'sedang',
    alergi VARCHAR(255),
    jumlah_makan INT DEFAULT 3,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES pengguna(id) ON DELETE CASCADE
);

CREATE TABLE pengaturan_notifikasi (
    id INT AUTO_INCREMENT PRIMARY KEY,
    user_id INT NOT NULL,
    pengingat_makan BOOLEAN DEFAULT TRUE,
    pengingat_minum BOOLEAN DEFAULT TRUE,
    pengingat_timbang BOOLEAN DEFAULT TRUE,
    waktu_pengingat TIME DEFAULT '08:00:00',
    sarapan_aktif BOOLEAN DEFAULT TRUE,
    sarapan_waktu TIME DEFAULT '07:00:00',
    siang_aktif BOOLEAN DEFAULT TRUE,
    siang_waktu TIME DEFAULT '12:00:00',
    malam_aktif BOOLEAN DEFAULT TRUE,
    malam_waktu TIME DEFAULT '18:00:00',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES pengguna(id) ON DELETE CASCADE
);

INSERT INTO menu_makanan (nama_makanan, kalori, protein, lemak, karbohidrat, kategori, tipe_diet, emoji) VALUES
-- Sarapan
('Bubur Ayam', 300, 15, 8, 45, 'Sarapan', 'normal', '🥣'),
('Nasi Uduk', 350, 8, 12, 52, 'Sarapan', 'normal', '🍚'),
('Lontong Sayur', 320, 10, 14, 42, 'Sarapan', 'normal', '🍲'),
('Ketoprak', 380, 14, 16, 48, 'Sarapan', 'vegetarian', '🍜'),
('Bubur Kacang Hijau', 280, 12, 5, 50, 'Sarapan', 'vegetarian', '🫘'),
('Roti Bakar Telur', 310, 16, 14, 32, 'Sarapan', 'normal', '🍞'),
('Overnight Oats', 320, 12, 8, 52, 'Sarapan', 'vegetarian', '🥣'),
('Sereal Susu', 250, 10, 6, 42, 'Sarapan', 'vegetarian', '🥛'),
('Pisang Goreng', 220, 3, 10, 32, 'Sarapan', 'vegetarian', '🍌'),
('Kue Cubir', 180, 4, 8, 24, 'Sarapan', 'vegetarian', '🧁'),

-- Makan Siang
('Nasi Goreng Sayur', 450, 18, 12, 65, 'Makan Siang', 'normal', '🍳'),
('Nasi Goreng Ayam', 520, 22, 16, 68, 'Makan Siang', 'normal', '🍛'),
('Nasi Padang (Ayam Pop)', 580, 30, 22, 60, 'Makan Siang', 'normal', '🍚'),
('Nasi Campur Bali', 490, 24, 18, 55, 'Makan Siang', 'normal', '🍱'),
('Mie Ayam', 420, 18, 14, 58, 'Makan Siang', 'normal', '🍜'),
('Bakso Sapi', 380, 22, 12, 48, 'Makan Siang', 'normal', '🍲'),
('Soto Ayam', 320, 20, 10, 40, 'Makan Siang', 'normal', '🍗'),
('Rawon', 360, 24, 14, 36, 'Makan Siang', 'normal', '🥩'),
('Gado-Gado', 350, 14, 18, 38, 'Makan Siang', 'vegetarian', '🥗'),
('Pecel Lele', 420, 28, 20, 35, 'Makan Siang', 'normal', '🐟'),
('Ayam Bakar', 450, 35, 18, 30, 'Makan Siang', 'normal', '🍗'),
('Ayam Goreng', 480, 32, 24, 28, 'Makan Siang', 'normal', '🍗'),
('Ikan Bakar + Sayur', 420, 35, 15, 40, 'Makan Siang', 'normal', '🐟'),
('Ikan Goreng', 390, 30, 18, 32, 'Makan Siang', 'normal', '🐟'),
('Ayam Panggang Salad', 380, 40, 10, 35, 'Makan Siang', 'normal', '🥗'),
('Capcay', 250, 12, 8, 36, 'Makan Siang', 'vegetarian', '🥬'),
('Tumis Kangkung', 120, 5, 7, 12, 'Makan Siang', 'vegetarian', '🥬'),
('Tahu Telur', 320, 18, 20, 18, 'Makan Siang', 'vegetarian', '🥚'),

-- Makan Malam
('Sup Ayam', 180, 16, 6, 18, 'Makan Malam', 'normal', '🍲'),
('Sup Ikan', 160, 20, 4, 14, 'Makan Malam', 'normal', '🐟'),
('Tumis Brokoli Tahu', 200, 14, 10, 18, 'Makan Malam', 'vegetarian', '🥦'),
('Pepes Ikan', 250, 28, 10, 12, 'Makan Malam', 'normal', '🐟'),
('Sayur Asem', 80, 3, 2, 14, 'Makan Malam', 'vegetarian', '🍲'),
('Sayur Lodeh', 150, 5, 8, 18, 'Makan Malam', 'vegetarian', '🥘'),
('Perkedel Tahu', 160, 10, 10, 12, 'Makan Malam', 'vegetarian', '🫘'),
('Sate Ayam', 350, 30, 18, 20, 'Makan Malam', 'normal', '🍢'),
('Sate Kambing', 380, 32, 22, 18, 'Makan Malam', 'normal', '🍢'),
('Gulai Ayam', 420, 26, 24, 28, 'Makan Malam', 'normal', '🍛'),
('Rendang Sapi', 480, 34, 28, 20, 'Makan Malam', 'normal', '🥩'),

-- Lauk/Pendamping
('Nasi Putih', 200, 4, 0.5, 45, 'Pokok', 'normal', '🍚'),
('Nasi Merah', 180, 4, 1, 38, 'Pokok', 'vegetarian', '🍚'),
('Nasi Kuning', 230, 5, 3, 48, 'Pokok', 'normal', '🍚'),
('Sayur Bayam', 50, 3, 1, 8, 'Lauk/Pendamping', 'vegetarian', '🥬'),
('Tempe Goreng', 150, 12, 8, 10, 'Lauk/Pendamping', 'vegetarian', '🫘'),
('Tempe Bacem', 140, 11, 7, 12, 'Lauk/Pendamping', 'vegetarian', '🫘'),
('Tahu Goreng', 130, 10, 9, 6, 'Lauk/Pendamping', 'vegetarian', '🧈'),
('Telur Dadar', 180, 14, 13, 1, 'Lauk/Pendamping', 'normal', '🥚'),
('Telur Ceplok', 160, 12, 12, 1, 'Lauk/Pendamping', 'normal', '🍳'),
('Perkedel Kentang', 180, 5, 12, 16, 'Lauk/Pendamping', 'normal', '🥔'),
('Sambal Goreng Kentang', 200, 4, 12, 22, 'Lauk/Pendamping', 'vegetarian', '🌶️'),
('Oseng Tempe', 170, 14, 9, 12, 'Lauk/Pendamping', 'vegetarian', '🫘'),
('Oseng Kacang Panjang', 100, 5, 6, 10, 'Lauk/Pendamping', 'vegetarian', '🫘'),
('Abon Sapi', 220, 24, 12, 4, 'Lauk/Pendamping', 'normal', '🥩'),
('Ikan Asin', 120, 18, 5, 0, 'Lauk/Pendamping', 'normal', '🐟'),

-- Minuman
('Smoothie Buah', 200, 3, 5, 38, 'Minuman', 'vegetarian', '🥤'),
('Jus Jeruk', 120, 2, 0, 28, 'Minuman', 'vegetarian', '🍊'),
('Jus Alpukat', 250, 3, 12, 34, 'Minuman', 'vegetarian', '🥑'),
('Jus Mangga', 180, 2, 1, 42, 'Minuman', 'vegetarian', '🥭'),
('Es Teh Tawar', 5, 0, 0, 1, 'Minuman', 'vegetarian', '🧋'),
('Es Teh Manis', 80, 0, 0, 20, 'Minuman', 'vegetarian', '🧋'),
('Kopi Hitam', 5, 0, 0, 0, 'Minuman', 'vegetarian', '☕'),
('Kopi Susu', 120, 4, 6, 12, 'Minuman', 'normal', '☕'),
('Susu Putih', 150, 8, 8, 12, 'Minuman', 'vegetarian', '🥛'),
('Susu Coklat', 200, 7, 8, 26, 'Minuman', 'vegetarian', '🥛'),
('Air Mineral', 0, 0, 0, 0, 'Minuman', 'vegetarian', '💧'),
('Jus Tomat', 60, 2, 0, 14, 'Minuman', 'vegetarian', '🍅'),
('Wedang Jahe', 40, 0, 0, 10, 'Minuman', 'vegetarian', '🫚'),
('Bandrek', 90, 1, 2, 18, 'Minuman', 'vegetarian', '☕'),

-- Camilan/Snack
('Pisang Goreng', 220, 3, 10, 32, 'Camilan', 'vegetarian', '🍌'),
('Singkong Goreng', 190, 2, 8, 30, 'Camilan', 'vegetarian', '🫘'),
('Martabak Telur', 350, 16, 20, 28, 'Camilan', 'normal', '🥞'),
('Martabak Manis', 380, 8, 14, 58, 'Camilan', 'vegetarian', '🥞'),
('Siomay', 280, 14, 12, 32, 'Camilan', 'normal', '🥟'),
('Batagor', 320, 12, 18, 30, 'Camilan', 'normal', '🥟'),
('Cireng', 240, 3, 12, 30, 'Camilan', 'vegetarian', '🫓'),
('Risol', 260, 6, 14, 28, 'Camilan', 'normal', '🥟'),
('Lumpia', 200, 6, 10, 24, 'Camilan', 'normal', '🥟'),
('Bakwan', 220, 5, 12, 26, 'Camilan', 'vegetarian', '🥟'),
('Tahu Isi', 180, 8, 10, 16, 'Camilan', 'vegetarian', '🧈'),
('Tempe Mendoan', 200, 10, 12, 16, 'Camilan', 'vegetarian', '🫘'),
('Kue Lapis', 160, 2, 4, 30, 'Camilan', 'vegetarian', '🍰'),
('Klepon', 140, 2, 3, 28, 'Camilan', 'vegetarian', '🍡'),
('Onde-Onde', 180, 3, 6, 30, 'Camilan', 'vegetarian', '🍡'),
('Kue Ape', 120, 2, 4, 22, 'Camilan', 'vegetarian', '🥞'),
('Cilok', 200, 8, 8, 26, 'Camilan', 'normal', '⚪'),
('Seblak', 350, 12, 16, 42, 'Camilan', 'normal', '🍜'),
-- Sarapan tambahan
('Nasi Liwet', 380, 10, 14, 54, 'Sarapan', 'normal', '🍚'),
('Lontong Balap', 340, 12, 10, 50, 'Sarapan', 'normal', '🍲'),
('Mie Goreng', 420, 14, 16, 56, 'Sarapan', 'normal', '🍜'),
('Bubur Sumsum', 250, 4, 8, 42, 'Sarapan', 'vegetarian', '🥣'),
('Roti Canai', 320, 8, 16, 38, 'Sarapan', 'normal', '🫓'),
('Lemper', 220, 8, 10, 26, 'Sarapan', 'normal', '🍙'),
('Arem-Arem', 200, 6, 8, 28, 'Sarapan', 'normal', '🫘'),
('Putu Ayu', 180, 3, 6, 30, 'Sarapan', 'vegetarian', '🧁'),
('Dadar Gulung', 160, 3, 5, 28, 'Sarapan', 'vegetarian', '🥞'),
-- Makan Siang tambahan
('Nasi Rames', 480, 22, 16, 60, 'Makan Siang', 'normal', '🍱'),
('Nasi Tutug Oncom', 420, 18, 14, 58, 'Makan Siang', 'vegetarian', '🍚'),
('Nasi Bakar', 460, 24, 16, 55, 'Makan Siang', 'normal', '🍙'),
('Nasi Jamblang', 440, 20, 14, 62, 'Makan Siang', 'normal', '🍚'),
('Ayam Betutu', 490, 36, 20, 32, 'Makan Siang', 'normal', '🍗'),
('Bebek Goreng', 520, 32, 24, 30, 'Makan Siang', 'normal', '🦆'),
('Gurame Bakar', 380, 34, 14, 28, 'Makan Siang', 'normal', '🐟'),
('Udang Goreng Tepung', 350, 28, 18, 22, 'Makan Siang', 'normal', '🦐'),
('Cumi Saus Padang', 320, 26, 14, 24, 'Makan Siang', 'normal', '🦑'),
('Empal Gepuk', 400, 28, 22, 20, 'Makan Siang', 'normal', '🥩'),
('Dendeng Balado', 420, 30, 24, 18, 'Makan Siang', 'normal', '🥩'),
('Semur Daging', 380, 28, 16, 30, 'Makan Siang', 'normal', '🥩'),
('Bihun Goreng', 380, 12, 14, 52, 'Makan Siang', 'normal', '🍜'),
('Kwetiau Goreng', 420, 14, 16, 56, 'Makan Siang', 'normal', '🍜'),
('Coto Makassar', 360, 24, 14, 34, 'Makan Siang', 'normal', '🍲'),
('Sop Konro', 380, 26, 16, 30, 'Makan Siang', 'normal', '🍲'),
('Pallubasa', 400, 28, 18, 32, 'Makan Siang', 'normal', '🍲'),
('Mie Kocok', 380, 20, 14, 46, 'Makan Siang', 'normal', '🍜'),
('Karedok', 220, 8, 12, 24, 'Makan Siang', 'vegetarian', '🥗'),
('Pecel Madiun', 350, 14, 16, 38, 'Makan Siang', 'vegetarian', '🥗'),
('Rujak Cingur', 380, 16, 18, 40, 'Makan Siang', 'normal', '🥗'),
-- Makan Malam tambahan
('Sop Iga Sapi', 420, 30, 20, 30, 'Makan Malam', 'normal', '🍲'),
('Sop Buntut', 400, 28, 18, 28, 'Makan Malam', 'normal', '🍲'),
('Tongseng Sapi', 380, 26, 18, 26, 'Makan Malam', 'normal', '🍛'),
('Nasi Timlo', 320, 18, 10, 42, 'Makan Malam', 'normal', '🍲'),
('Tahu Telur Bumbu Kacang', 350, 18, 22, 20, 'Makan Malam', 'vegetarian', '🥚'),
('Gudeg', 450, 8, 18, 64, 'Makan Malam', 'vegetarian', '🍛'),
('Bothok Tahu Tempe', 200, 14, 12, 14, 'Makan Malam', 'vegetarian', '🫘'),
('Kering Tempe', 180, 12, 10, 14, 'Makan Malam', 'vegetarian', '🫘'),
('Urap Sayur', 120, 5, 7, 12, 'Makan Malam', 'vegetarian', '🥬'),
('Tumis Tauge Tahu', 160, 10, 8, 16, 'Makan Malam', 'vegetarian', '🥬'),
('Cah Kangkung', 80, 4, 4, 10, 'Makan Malam', 'vegetarian', '🥬'),
('Ayam Suwir Pedas', 280, 32, 14, 8, 'Makan Malam', 'normal', '🍗'),
-- Lauk/Pendamping tambahan
('Tahu Gejrot', 120, 8, 7, 10, 'Lauk/Pendamping', 'vegetarian', '🧈'),
('Tempe Orek', 160, 12, 9, 12, 'Lauk/Pendamping', 'vegetarian', '🫘'),
('Perkedel Jagung', 170, 5, 10, 18, 'Lauk/Pendamping', 'vegetarian', '🌽'),
('Sambal Terasi', 40, 2, 3, 4, 'Lauk/Pendamping', 'vegetarian', '🌶️'),
('Acar Timun Wortel', 30, 1, 0, 6, 'Lauk/Pendamping', 'vegetarian', '🥒'),
('Kerupuk Udang', 80, 2, 4, 10, 'Lauk/Pendamping', 'normal', '🦐'),
-- Minuman tambahan
('Jus Jambu', 100, 1, 0, 24, 'Minuman', 'vegetarian', '🍈'),
('Jus Sirsak', 110, 1, 0, 26, 'Minuman', 'vegetarian', '🍈'),
('Jus Wortel', 70, 2, 0, 16, 'Minuman', 'vegetarian', '🥕'),
('Es Campur', 280, 3, 6, 52, 'Minuman', 'vegetarian', '🧋'),
('Es Teler', 300, 4, 8, 54, 'Minuman', 'vegetarian', '🥥'),
('Cendol', 220, 2, 5, 42, 'Minuman', 'vegetarian', '🍵'),
('Dawet', 180, 1, 3, 36, 'Minuman', 'vegetarian', '🍵'),
('Sop Buah', 190, 2, 4, 36, 'Minuman', 'vegetarian', '🍉'),
('Kolak Pisang', 250, 2, 6, 48, 'Minuman', 'vegetarian', '🍌'),
('Wedang Ronde', 160, 2, 3, 32, 'Minuman', 'vegetarian', '🫚'),
('Sekoteng', 180, 2, 4, 34, 'Minuman', 'vegetarian', '🥜'),
('Bir Pletok', 60, 0, 0, 14, 'Minuman', 'vegetarian', '🧴'),
-- Camilan tambahan
('Kue Lumpur', 190, 3, 8, 28, 'Camilan', 'vegetarian', '🧁'),
('Kue Pukis', 180, 4, 6, 28, 'Camilan', 'vegetarian', '🥞'),
('Bika Ambon', 220, 4, 8, 36, 'Camilan', 'vegetarian', '🍯'),
('Bolu Kukus', 200, 4, 6, 34, 'Camilan', 'vegetarian', '🧁'),
('Wingko', 250, 4, 12, 34, 'Camilan', 'vegetarian', '🥥'),
('Nagasari', 160, 2, 4, 30, 'Camilan', 'vegetarian', '🍌'),
('Kue Putu', 140, 2, 2, 30, 'Camilan', 'vegetarian', '🍚'),
('Misro', 190, 3, 8, 28, 'Camilan', 'vegetarian', '🫘'),
('Combro', 180, 4, 8, 24, 'Camilan', 'vegetarian', '🫘'),
('Pastel', 260, 6, 14, 28, 'Camilan', 'normal', '🥟'),
('Sosis Solo', 220, 10, 12, 20, 'Camilan', 'normal', '🥟'),
('Bakpia', 170, 3, 6, 28, 'Camilan', 'vegetarian', '🥮'),
('Kue Pancong', 200, 3, 8, 30, 'Camilan', 'vegetarian', '🥞'),
('Es Krim', 200, 4, 12, 22, 'Camilan', 'vegetarian', '🍦'),
('Agar-Agar Buah', 120, 2, 0, 28, 'Camilan', 'vegetarian', '🍮'),
('Puding Coklat', 180, 4, 8, 24, 'Camilan', 'vegetarian', '🍮'),
('Getuk', 200, 2, 6, 36, 'Camilan', 'vegetarian', '🫘'),
('Gemblong', 220, 3, 10, 32, 'Camilan', 'vegetarian', '🫘'),
('Lupis', 190, 3, 4, 38, 'Camilan', 'vegetarian', '🍚');

CREATE TABLE laporan_analisis (
    id INT AUTO_INCREMENT PRIMARY KEY,
    user_id INT NOT NULL,
    periode ENUM('harian', 'mingguan', 'bulanan') NOT NULL,
    start_date DATE NOT NULL,
    end_date DATE NOT NULL,
    total_kalori INT DEFAULT 0,
    total_protein DECIMAL(10,1) DEFAULT 0,
    total_karbohidrat DECIMAL(10,1) DEFAULT 0,
    total_lemak DECIMAL(10,1) DEFAULT 0,
    rata_rata_kalori INT DEFAULT 0,
    rata_rata_berat DECIMAL(5,1) DEFAULT NULL,
    hari_tercapai INT DEFAULT 0,
    total_hari INT DEFAULT 0,
    data_lengkap JSON DEFAULT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES pengguna(id) ON DELETE CASCADE,
    UNIQUE KEY unique_user_periode (user_id, periode, end_date)
);

-- Tag vegan items (plant-based: minuman buah, camilan nabati, sayuran)
UPDATE menu_makanan SET tipe_diet = 'vegan' WHERE nama_makanan IN (
  'Jus Jeruk', 'Jus Alpukat', 'Jus Mangga', 'Jus Tomat', 'Jus Jambu', 'Jus Sirsak', 'Jus Wortel',
  'Es Teh Tawar', 'Es Teh Manis', 'Kopi Hitam', 'Air Mineral', 'Wedang Jahe', 'Bandrek',
  'Es Campur', 'Es Teler', 'Cendol', 'Dawet', 'Sop Buah', 'Kolak Pisang', 'Wedang Ronde', 'Sekoteng',
  'Bir Pletok', 'Pisang Goreng', 'Singkong Goreng', 'Cireng', 'Kue Lapis', 'Klepon', 'Onde-Onde',
  'Kue Ape', 'Tahu Isi', 'Tempe Mendoan', 'Kue Putu', 'Misro', 'Combro', 'Bakpia', 'Kue Pancong',
  'Agar-Agar Buah', 'Puding Coklat', 'Getuk', 'Gemblong', 'Lupis', 'Nagasari', 'Kue Pukis',
  'Bika Ambon', 'Bolu Kukus', 'Wingko', 'Gado-Gado', 'Karedok', 'Pecel Madiun', 'Sayur Asem',
  'Sayur Lodeh', 'Tumis Kangkung', 'Capcay', 'Urap Sayur', 'Cah Kangkung', 'Gudeg', 'Kering Tempe',
  'Oseng Tempe', 'Oseng Kacang Panjang', 'Sambal Goreng Kentang', 'Tumis Brokoli Tahu',
  'Bothok Tahu Tempe', 'Tumis Tauge Tahu', 'Tahu Gejrot', 'Tempe Orek', 'Tempe Bacem',
  'Tempe Goreng', 'Tahu Goreng', 'Perkedel Jagung', 'Sambal Terasi', 'Acar Timun Wortel',
  'Lontong Sayur', 'Ketoprak', 'Bubur Kacang Hijau', 'Lontong Balap', 'Bubur Sumsum', 'Rujak Cingur'
);
